### DISCUSSION TITLE
Upload multiple reports with different flags using single config

### DISCUSSION THREAD

**Discussion by Ekleog-NEAR** [codecov/feedback#168] [Ideas]
Hello!

I’ll start with, this is a duplicate of closed-by-author codecov/codecov-action#243, and of the discussion that happened after codecov/codecov-action#50 was closed.

I’d like to upload multiple reports with different flags. It currently seems to basically require calling the codecov actions multiple times. However, it results in a lot of copy-paste, and workarounds like using `steps: fromJson()` with a custom generator script is even more painful.

Would it be possible to upload multiple reports with different flags? I’m thinking of a syntax like:
```yml
- uses: actions/codecov-action@v??
  with:
    token: ${{ secrets.CODECOV_TOKEN }}
    fail_ci_if_error: true
    files:
      - { path: "unit-tests.json", flags: "unit-tests" }
      - { path: "integration-tests.json", flags: "integration-tests" }
```

What do you think?

**Comment by Ekleog-NEAR** [comment]
Also, for some context: we currently have 11 reports, because of the test matrix and splitting unit and integration tests, and I think it’s quite likely to grow.

Having the ability to take all in the `files` argument would hopefully also allow using `files: fromJson()` and auto-computing the list of files with flags, for the bigger workloads :)

**Comment by thomasrockhu-codecov** [comment]
@Ekleog-NEAR, no this is not possible as specified. You can instead run the action twice, each specifying a file and a flag

e.g.
```
- uses: actions/codecov-action@??
  with:
    token: ${{ secrets.CODECOV_TOKEN }}
    fail_ci_if_error: true
    files:
      - unit-tests.json
    flags:
      - unit-tests

- uses: actions/codecov-action@??
  with:
    token: ${{ secrets.CODECOV_TOKEN }}
    fail_ci_if_error: true
    files:
      - integration-tests.json
    flags:
      - integration-tests
```

I would recommend trying this with `v4-beta`, but it should work on `v3` too
