### DISCUSSION TITLE
GitHub card not showing diff coverage anymore.

### DISCUSSION THREAD

**Discussion by mikebronner** [codecov/feedback#203] [Q&A] [answered]
When coming to work after the Christmas holidays we noticed that the GitHub PR cards are no longer showing patch coverage percentage, but now show number of lines missed.

<img width="948" alt="Screenshot 2023-12-26 at 11 14 57 AM" src="https://github.com/codecov/feedback/assets/1791050/edce65df-46ac-4516-aadf-18d4817a142f">

Previously looked like (see the diff coverage specifically):

<img width="960" alt="Screenshot 2023-12-26 at 11 17 32 AM" src="https://github.com/codecov/feedback/assets/1791050/df2d3fac-e5e6-4990-a68d-91ea742ca99a">

Is this something that can be configured? This change is a point of friction, because we have code coverage requirements as part of our Definition of Done, and was very easy to confirm the way it was before Christmas, both for the developer and for the reviewer.

It appears there is some configuration mentioned here: https://docs.codecov.com/docs/pull-request-comments
Our `codecov.yml` file has not been changed:
```yml
codecov:
  require_ci_to_pass: false
  allow_coverage_offsets: true

comment:
  layout: "reach,diff,flags,tree,betaprofiling"
  show_critical_paths: true

coverage:
  precision: 2
  round: down
  range: "90...100"

profiling:
  fixes:
  - "::app/"
```
