### DISCUSSION TITLE
How to add `informational` mode to this codecov.yml

### DISCUSSION THREAD

**Discussion by buondevid** [codecov/feedback#355] [Q&A]
We tried adding `informational` in the places you see, but it doesn't look to be working. What are we doing wrong? Thanks

```yaml
# https://docs.codecov.com/docs/flags#recommended-automatic-flag-management
flag_management:
  default_rules:
    carryforward: true
    statuses:
      - type: project
        target: auto
        threshold: 0.1%
        informational: true
      - type: patch
        target: 90%
        informational: true

  individual_flags:
    - name: frontend
      paths:
        - "frontend/"
      informational: true
    - name: backend
      paths:
        - "k/"
      informational: false
    - name: graphql
      paths:
        - "frontend/src/api/generated.ts"
        - "k/apps/**/graphql/"
        - "k/apps/**/mutations.py"
        - "k/apps/**/queries.py"
        - "k/apps/**/types.py"
      informational: true

github_checks:
  annotations: false

ignore:
  - "frontend/jest.config.*.js"
  - "frontend/webpack.*.js"
  - "gunicorn_conf.py"
  - "k/**/migrations/*.py"
  - "k/manage.py"
  - "k/wsgi.py"
  ```

**Comment by drazisil-codecov** [comment]
Hi @buondevid ,

To clarify, when you say "not working", the checks are coming back as failed?

**Reply by buondevid** [reply]
yes, that's correct!

**Reply by drazisil-codecov** [reply]
The config looks correct. Can you share the SHA so I can take a look at the logs?

**Reply by buondevid** [reply]
they are private repos unfortunately!

This is what it looks like on GH on a random PR
![image](https://github.com/codecov/feedback/assets/36935593/fd3c88e2-225f-4076-a0de-b56f255e2d52)

And we have this current `codecov.yml` config:
```yaml
# https://docs.codecov.com/docs/flags#recommended-automatic-flag-management
flag_management:
  default_rules:
    carryforward: true
    statuses:
      - type: project
        target: auto
        threshold: 0.1%
        informational: true
      - type: patch
        target: 90%
        informational: true

  individual_flags:
    - name: frontend
      paths:
        - "frontend/"
      informational: true
    - name: backend
      paths:
        - "k/"
      informational: false
    - name: graphql
      paths:
        - "frontend/src/api/generated.ts"
        - "k/apps/**/graphql/"
        - "k/apps/**/mutations.py"
        - "k/apps/**/queries.py"
        - "k/apps/**/types.py"
      informational: true

github_checks:
  annotations: false

ignore:
  - "frontend/jest.config.*.js"
  - "frontend/webpack.*.js"
  - "gunicorn_conf.py"
  - "k/**/migrations/*.py"
  - "k/manage.py"
  - "k/wsgi.py"

```

**Reply by drazisil-codecov** [reply]
> they are private repos unfortunately!
Yes, but the SHA by itself can't be used by anyone else, nor reveal any information. (except in our internal logs)

In any case, the yaml structure is incorrect. I apologize for missing this on first pass, it was a failed attempt at too much multitasking. `informational` is a status attribute , so it needs to be nested under the flag like so:

```
    - name: backend
      paths:
        - "k/"
      statuses:
        - type: project
          informational: true
```

There's a link to our validator at the top of https://docs.codecov.com/docs/codecovyml-reference, or you can use the VSCode extenstion https://marketplace.visualstudio.com/items?itemName=Codecov.codecov

I hope this helps!

**Reply by buondevid** [reply]
thanks it helped with the flags reports, but not with the base ones
<img width="901" alt="image" src="https://github.com/codecov/feedback/assets/36935593/a80d0667-04c1-4562-9501-cc612d666414">

Anything else we are setting wrong in our config? The extension I installed doesn't give me any more errors

**Reply by drazisil-codecov** [reply]
It passed validation. If I could have a SHA I can check how it's being parsed when we go to send notifications, but that should be valid. 

It might actually be a bug, since it doesn't look like your targets are the correct percentages either.

If you add
```
coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0.1%
        informational: true
    patch:
        target: 90%
        informational: true
```

To the bottom, does that work? (please double check the indentation is correct in this saple)

**Reply by cyphar** [reply]
I've been running into this issue for a while in https://github.com/cyphar/libpathrs and in https://github.com/cyphar/libpathrs/pull/379 I tried adding duplicate entries for coverage status in the top-level `coverage` field and that appears to fix the issue. This is obviously less than ideal because it also means I need to re-define all of the components again.

https://github.com/cyphar/libpathrs/pull/378 is a PR that shows the failure mode, in particular commit cyphar/libpathrs@1228e800c4b5cfc2919c1a7442bcdcd6297d349a.

Here is the new config I ended up with:

```yaml
comment:
  layout: "reach, diff, components, files"
  require_changes: true
  behavior: once
  branches:
    - main

component_management:
  default_rules:
    statuses:
      - type: project
        target: auto
      - type: patch
        target: auto
        informational: true
  individual_components:
    - component_id: pathrs
      name: pathrs
      paths:
        - "src/**"
        - "!src/capi/**"
      statuses:
        - type: project
          target: 80%
          threshold: 0%
        - type: patch
          target: auto
          informational: true
    - component_id: pathrs-capi
      name: libpathrs.so
      paths:
        - "src/capi/**"
      statuses:
        - type: project
          target: 80%
          threshold: 0%
        - type: patch
          target: auto
          informational: true

coverage:
  range: 60..95
  status:
    project:
      default:
        target: auto
      pathrs:
        target: 80%
        threshold: 0%
        paths:
          - "src/**"
          - "!src/capi/**"
      libpathrs.so:
        target: 80%
        threshold: 0%
        paths:
          - "src/capi/**"
    patch:
      default:
        target: auto
        informational: true

github_checks:
  annotations: true
```

Hopefully this helps get the issue resolved...
