### DISCUSSION TITLE
Bitbucket pull requests are not beeing updated woth codecov comments

### DISCUSSION THREAD

**Discussion by Ezols** [codecov/feedback#544] [General]
Hey,

Please assist me, i dont know what is the problem, why bitbucket comments are not being created.

Configuration kinda checkout:
<img width="978" alt="image" src="https://github.com/user-attachments/assets/28b998ce-90c3-459b-9c9e-24c190d8bd77">

using this codecov.yml configuration from project:

```yml
codecov:
  bot: xxxxx
coverage:
  status:
    project:
      default:
        target: 50%
        threshold: 0.01%
        base: auto
    patch:
      default:
        target: 50%
        threshold: 0.01%
        base: auto

comment:
  layout: "newheader, diff, flags, files"
  behavior: new
  require_changes: false  # if true: only post the comment if coverage changes
  require_base: false     # [true :: must have a base report to post]
  require_head: false      # [true :: must have a head report to post]
  hide_project_coverage: false # [true :: only show coverage on the git diff aka patch coverage]
  branches:
      - all
```      
      
     
  i see this config in codecov.io projects configuration:

```yml
codecov:
  bot: edvardsozols
comment:
  behavior: new
  branches:
    - ^all$
  hide_project_coverage: false
  layout: newheader, diff, flags, files
  require_base: false
  require_changes:
   - 0
  require_head: false
coverage:
  status:
    patch:
      default:
        base: auto
        target: 50.0
        threshold: 0.01
    project:
      default:
        base: auto
        target: 50.0
        threshold: 0.01
```

one example which looks ok, but dont have comment in pr:
<img width="1569" alt="image" src="https://github.com/user-attachments/assets/a8a9e33a-f34f-406e-9acb-29fbdf6e924f">

Please let me know what else i need to check/provide to idenfity and fix this issue or mistake.
