### ISSUE TITLE
Documentation for empty-upload

### ISSUE THREAD

**Issue by thomasrockhu-codecov** [codecov/feedback#108]
**What product do you want to improve?**
CLI

**Is your feature request related to a problem? Please describe.**
There aren't really good docs for how to deploy `empty-upload` so that I get status checks when I don't upload any coverage.

**Describe the solution you'd like**
Getting a passing status check when no coverage is uploaded

**Describe alternatives you've considered**

**Additional context**
This is getting pulled from this [community board post](https://community.codecov.com/t/i-would-like-to-skip-the-codecov-when-source-code-when-files-unrelated-to-the-tests-are-modified/4433).

**Comment by james-kessler** [comment]
👍 for this request from my organization as well

**Comment by dpanici** [comment]
Any update on this? Or any link to a repo which is using this feature so we may see how it is working in practice, even if the documentation is not clear?

**Comment by cristian-vallejos** [comment]
Up to @dpanici question 🙌

**Comment by drazisil-codecov** [comment]
https://github.com/codecov/engineering-team/issues/2365 is related, but as soon as we make sure this is actually working correctly, (I think we are almost there), we will definitely get this documented correctly.

It's partly here https://docs.codecov.com/docs/cli-options#empty-upload 

I'd scold @thomasrockhu-codecov for not tagging it correctly, but I think this issue predates the "Docs" tag.

Thanks for the ping!

**Comment by YigitElma** [comment]
Is this possible to achieve via `codecov.yml`? I have something like this,
```
comment:             
  layout: " diff, flags, files"
  behavior: default
  require_changes: false  
  require_base: true       
  require_head: true     
  after_n_builds: 14   # wait for tests to complete
coverage:
  status:
    patch:
      default:
        informational: false
        if_not_found: success 
    project:
      default:
        informational: false
        threshold: 2.0
        if_not_found: success 
```

I was expecting the `after_n_builds` and `if_not_found` to work together to achieve this. In my use case, I have some workflows for pytest that are skipped based on a label on the PR. Since they are skipped, the status is always `Expected — Waiting for status to be reported`, even though 14 workflows are completed.
