### ISSUE TITLE
`if` statements reporting as `partial` when both cases are covered.

### ISSUE THREAD

**Issue by imnasnainaec** [codecov/feedback#127]
The following screenshots are from https://app.codecov.io/gh/sillsdev/TheCombine of reports generated by `react-scripts test --coverage --watchAll=false` and uploaded with the Codecov GitHub Action (v3.1.4).

![image (1)](https://github.com/codecov/feedback/assets/6411521/1c7808ae-03a8-480b-9b10-53aebbea1545)
![Screenshot 2023-10-25 084526](https://github.com/codecov/feedback/assets/6411521/d51ed8fc-2d77-4c56-b274-a67e685dc696)

It appears this issue was reported in the old Community Board but not yet resolved: https://community.codecov.com/t/false-partials-in-code-coverage-javascript-typescript/2957

**Comment by drazisil-codecov** [comment]
Hi @imnasnainaec ,

What report format are you using? There's this PR https://github.com/codecov/worker/pull/155 that affects partial coverage, I wonder if it will help you.

**Comment by imnasnainaec** [comment]
@drazisil-codecov The coverage file `clover.xml` begins:
```
<?xml version="1.0" encoding="UTF-8"?>
<coverage generated="1698239413116" clover="3.2.0">
  <project timestamp="1698239413116" name="All files">
    <metrics statements="6369" coveredstatements="2817" conditionals="2937" coveredconditionals="1160" methods="2240" coveredmethods="898" elements="11546" coveredelements="4875" complexity="0" loc="6369" ncloc="6369" packages="89" files="497" classes="497"/>
    <package name="src">
      <metrics statements="23" coveredstatements="16" conditionals="12" coveredconditionals="4" methods="6" coveredmethods="4"/>
      <file name="browserRouter.tsx" path="C:\Users\danie\sillsdev\TheCombine\src\browserRouter.tsx">
        <metrics statements="6" coveredstatements="5" conditionals="4" coveredconditionals="2" methods="1" coveredmethods="1"/>
```

We upload it in [a GitHub Action workflow](https://github.com/sillsdev/TheCombine/blob/master/.github/workflows/frontend.yml#L78-L84):
```
      - name: Upload coverage report
        uses: codecov/codecov-action@eaaf4bedf32dbdc6b720b63067d99c4d77d6047d # v3.1.4
        with:
          fail_ci_if_error: true
          files: clover.xml
          flags: frontend
          name: Frontend
```

And here's our `codecov.yml`: https://github.com/sillsdev/TheCombine/blob/master/codecov.yml

I'm not sure if that answers your question.
