### ISSUE TITLE
Go report 100% coverage while codecov reports less

### ISSUE THREAD

**Issue by sylr** [codecov/feedback#154]
**Describe the bug**

I have a use case where `go test -coverprofile=atomic` reports a 100% coverage for a package but it shows as 98% only on codecov.

**To Reproduce**
```go
type Matcher interface {
	Accept(book Book, order Order) bool
	Match(book Book, order Order, report *ExecutionReport) 
}

type Continous struct {}

func (c Continous) Accept(book Book, order Order) bool {
	// 100% covered code
	return true
}

func (c Continous) Match(book Book, order Order, report *ExecutionReport)  {
	// 100% covered code
}

type Close struct {}

func (c Close) Accept(book Book, order Order) bool {
	// 100% covered code
	return false
}

func (c Close) Match(book Book, order Order, report *ExecutionReport)  {
	// Since Close.Accept always returns false, the close.Match is never called
	// and therefore can not be covered in tests.
}

```

**Expected behavior**

Codecov to report 100% coverage like `go test` does.

**Screenshots**

## Go
<img width="678" alt="image" src="https://github.com/codecov/feedback/assets/153052/ce77a08c-5651-4f33-8aae-e3128cb6c296">

## Codecov
![image](https://github.com/codecov/feedback/assets/153052/36bdfe33-fc60-4b1c-bfb3-72a9c276b036)

**Additional context**

**Comment by thomasrockhu-codecov** [comment]
@sylr how are you uploading coverage reports to Codecov?

**Comment by sylr** [comment]
Github Actions:

```yaml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverage.txt
```
