### ISSUE TITLE
[self-hosted] Login Redirecting to localhost

### ISSUE THREAD

**Issue by drazisil-codecov** [codecov/feedback#170]
### Discussed in https://github.com/codecov/feedback/discussions/169

<div type='discussions-op-text'>

<sup>Originally posted by **chaseconey** November 29, 2023</sup>

## Overview

Seeing a new issue popping up after doing a clean install.

Logging in with the "Login with GitHub" button goes through the auth flow, but ends by redirecting to `localhost/gh`.

## Context

Here is the chain of redirects:

1. https://mydomain.com/login/gh
2. https://github.com/login/oauth/authorize
3. https://mydomain.com/login/github?code=x&state=x
4. http://localhost/gh

and here is my docker-compose file (truncated for brevity):

```yaml
version: "3"

services:
  gateway:
    image: codecov/self-hosted-gateway:latest-calver
    volumes:
      - ./config:/config
    ports:
      - "${CODECOV_PORT-80}:8080"
    environment:
      - CODECOV_GATEWAY_MINIO_ENABLED=true
      - CODECOV_DEFAULT_HOST=frontend
      - CODECOV_DEFAULT_PORT=8080
      - CODECOV_DEFAULT_SCHEME=http
      - CODECOV_DEFAULT_HOST_HEADER="%[req.hdr(Host)]"
    networks:
      - codecov
    depends_on:
      - api
      - frontend

  frontend:
    image: codecov/self-hosted-frontend:latest-calver
    environment:
      - CODECOV_BASE_HOST=mydomain.com
      - CODECOV_API_HOST=mydomain.com
      - CODECOV_IA_HOST=mydomain.com
      - CODECOV_SCHEME=https
    volumes:
      - ./config:/config
    ports:
      - "8080"
    networks:
      - codecov

  api:
    image: codecov/self-hosted-api:latest-calver
    environment:
      - RUN_ENV=ENTERPRISE
    volumes:
      - ./config:/config
    networks:
      - ...
```

Any ideas what might be causing this?</div>
