### ISSUE TITLE
Merged report isn't recognized

### ISSUE THREAD

**Issue by Gigas002** [codecov/feedback#201]
I'm running tests for all of my dotnet projects in a matrix loop in Github CI pipeline. After each test is complete, I upload the corresponding coverage report into artifacts, and after all tests are complete, I download the artifacts and upload them to codecov with action:

```yaml
      - name: codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          files: coverage/**/*.xml
```

This uploads the coverage files onto website, and I can see them on the [commit page](https://app.codecov.io/github/Gigas002/dotnet_gh_deploy/commit/3921d1bc36255948e371c23aff5f95697eeda96b).
However, I get an error `unusable report` and a 0% coverage. When I upload only one coverage file it's OK, e.g. [this commit](https://app.codecov.io/github/Gigas002/dotnet_gh_deploy/commit/f4929cd7483f8f3528af5fdd9db666f1abbaca0e).

My first test covers the `Deploy.Core` and `Deploy.Dummy` libs, and the second test covers the `Deploy.Server` app. Since it also references the `Deploy.Core`, it's included into report, and it's coverage is very low for this test project, since it's not a target here.
I suspect, that having this project twice in different reports from different tests breaks merging. The example of resulting file from is available on a commits page above.

Is this a bug? Or is there a way to fix it in my CI/CD pipeline/test code?
