### ISSUE TITLE
Codecov not posting pull request comments or checks

### ISSUE THREAD

**Issue by andreiz** [codecov/feedback#379]
**Describe the bug**
I have configured self-hosted codecov and Github app according to [Self-Hosted Install Guide](https://docs.codecov.com/docs/installing-codecov-self-hosted). The app has appropriate permissions and the PEM file is accessible inside the docker containers. I am following the Github tutorial from Codecov docs.

The Github workflow file uses `codecov-action`:

```
    - name: Upload coverage reports to Codecov with GitHub Action
      uses: codecov/codecov-action@v4.2.0
      with:
        url: https://codecov.bbbb.ccc
        fail_ci_if_error: true
        token: ${{ secrets.CODECOV_TOKEN }}
        verbose: true
```

**To Reproduce**
Create a branch, make changes, and push, then create PR.

**Expected behavior**
Codecov posts comments on status checks as per the tutorial:

![image](https://github.com/codecov/feedback/assets/40809/24662755-5503-49de-ba93-10a515c44129)

However, in my case the first two checks pass, but there are no comments from Codecov with the coverage etc

<img width="913" alt="image" src="https://github.com/codecov/feedback/assets/40809/71a161ec-41b9-4212-9b24-27ef7ed92588">

**Additional context**
Not sure if related, but the Codecov UI commits tab for the repo says "commit message unavailable" and "no patch uploaded":

<img width="1266" alt="image" src="https://github.com/codecov/feedback/assets/40809/00922aab-6911-48f0-a084-284a7133cba3">

The log from the `codecov-action` upload step:

[0_Test python API.txt](https://github.com/codecov/feedback/files/15327302/0_Test.python.API.txt)
