### ISSUE TITLE
Checks are failing even thought they are informational

### ISSUE THREAD

**Issue by nwalters512** [codecov/feedback#386]
**Describe the bug**

I've configured the project and patch status checks to be informational:

```yml
coverage:
  status:
    project:
      informational: true
    patch:
      informational: true
```

The documentation on https://docs.codecov.com/docs/commit-status states that the status checks should _never_ fail when marked as informational:

> Use Codecov in informational mode. Default is `false`. If `true` is specified the resulting status will pass no matter what the coverage is or what other settings are specified. Informational mode is great to use if you want to expose codecov information to other developers in your pull request without necessarily gating PRs on that information.

However, they're both failing on this PR: https://github.com/PrairieLearn/PrairieLearn/pull/9743

**Environment:**
 - Browser: N/A
 - System: CI (GitHub Actions)

**To Reproduce**

I'm not entirely sure what to put here; I think I've given as much information as I can. A repo containing the above YAML configuration does not behave as the documentation says it should. This is visible on https://github.com/PrairieLearn/PrairieLearn/pull/9743.

**Expected behavior**

Per the documentation, informational checks should never fail.

**Screenshots**

<img width="940" alt="Screenshot 2024-05-17 at 17 32 46" src="https://github.com/codecov/feedback/assets/1476544/b14eb118-6352-4996-8d13-ae292ec20c5f">

**Comment by drazisil-codecov** [comment]
Hi @nwalters512 ,

You are missing the check's name.

<img width="493" alt="image" src="https://github.com/codecov/feedback/assets/71270647/db9d529f-c4f5-4545-9aa0-decf21be53dc">


```
coverage:
  status:
    project:
      # Don't fail the status check if coverage decreases.
      informational: true # I am the name of the check.
    patch:
      # Don't fail the status check if coverage decreases.
      informational: true
```

Should be

```
coverage:
  status:
    project:
      # Don't fail the status check if coverage decreases.
      default: # This is the check name. It doesn't have have to be default , it just needs to exist.
        informational: true
    patch:
      # Don't fail the status check if coverage decreases.
      default: 
        informational: true
```
