### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by superlopuh** [codecov/feedback#388]
I recently switched to `codecov/codecov-action@v4`, and since then I've not been seeing any line by line coverage, on the website or in any of the actions.

Here is a recent example:

https://github.com/xdslproject/xdsl/pull/2621

Here's the relevant action for that PR:

https://github.com/xdslproject/xdsl/actions/runs/9188980377/job/25269976878

And the config:

```
    - name: Upload coverage to Codecov
      if: matrix.python-version == '3.10'
      uses: Wandalen/wretry.action@v1
      with:
        action: codecov/codecov-action@v4
        attempt_delay: 10000
        attempt_limit: 10
        with: |
          fail_ci_if_error: true
          verbose: true
          files: coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}
```

On the codecov website, I see this for every file:

```
There was a problem getting the source code from your provider. Unable to show line by line coverage.
```

How do we get code coverage back?
