### ISSUE TITLE
I guess I am too stupid to use codecov

### ISSUE THREAD

**Issue by hunterhogan** [codecov/feedback#628]
```
name: Python Tests
on: [push, pull_request]
jobs:
  get-python-versions:
    runs-on: ubuntu-latest
    outputs:
      python-versions: ${{ steps.get-python-versions.outputs.versions }}
    steps:
      - uses: actions/checkout@v4
      - name: Install toml parser
        run: pip install tomli packaging
      - id: get-python-versions
        run: |
          VERSIONS=$(python -c "
          import tomli, json
          import packaging.specifiers
          import packaging.version

          with open('pyproject.toml', 'rb') as readStreamBinaryMode:
            specifierPython = packaging.specifiers.SpecifierSet(tomli.load(readStreamBinaryMode)['project']['requires-python'])

          listCandidateVersionsInSpecifier = []
          for majorVersion in range(2, 12):
            for minorVersion in range(0, 40):
              versionCandidate = packaging.version.Version(f'{majorVersion}.{minorVersion}')
              if versionCandidate in specifierPython:
                listCandidateVersionsInSpecifier.append(f'{majorVersion}.{minorVersion}')

          print(json.dumps(listCandidateVersionsInSpecifier))
          ")
          echo "versions=$(echo $VERSIONS | jq -c .)" >> $GITHUB_OUTPUT
  build:
    needs: get-python-versions
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ${{fromJson(needs.get-python-versions.outputs.python-versions)}}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ".[testing]"

      - name: Run tests with coverage
        run: pytest

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v3
        with:
          name: coverage-data
          path: tests/coverage/coverage.xml
```

```
name: Codecov Coverage
on:
  workflow_run:
    workflows: ["Python Tests"]
    types: [completed]

jobs:
  coverage:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download coverage artifacts
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: ${{ github.event.workflow_run.workflow_id }}
          name: coverage-data
      - name: Upload to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: tests/coverage/coverage.xml
          fail_ci_if_error: true
```

fail, again https://github.com/hunterhogan/mapFolding/actions/runs/12835036303

and again https://github.com/hunterhogan/mapFolding/actions/runs/12835275029

and idk how many times last month

**Comment by thomasrockhu-codecov** [comment]
@hunterhogan just a few things that might help

1. Try using the `v5` action
2. You will need to add the `CODECOV_TOKEN` as a secret to the repository as well as in the action call like
```
- name: Upload to Codecov
  uses: codecov/codecov-action@v5
  with:
    fail_ci_if_error: true
    token: ${{ secrets.CODECOV_TOKEN }}
    verbose: true
```
3. As above, remove the `files` arg, I'm guessing that the downloaded artifact is not actually where you think it is. Perhaps do an `ls` to see if it actually exists there.
