### ISSUE TITLE
[Self-Hosted]: Upload failed: Invalid request parameters - unallowed value github_enterprise

### ISSUE THREAD

**Issue by michaelfedell** [codecov/feedback#638]
**Describe the bug**
Uploading the coverage report fails with an error: `Upload failed: Invalid request parameters`. 

**Environment (please complete the following information):**
 - CodeCov Self Hosted (running on kubernetes
 - GitHub Enterprise Server (3.14)
 - CodeCov GitHub Action @v5

**To Reproduce**
1. CodeCov Self-Hosted with GitHub App on GitHub Enterprise Server
2. Follow the "github-tutorial" repository from [codecov docs](https://docs.codecov.com/docs/github-tutorial)
3. Error on upload from CI

**Expected behavior**
I expect the GitHub Action to properly upload a coverage report.

**Additional context**

I can successfully log in to our self-hosted codecov instance and see no other error or warning logs in any of the codecov containers.

GitHub Action Workflow
```
name: API workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: arc-runner-default
    name: Test python API
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install requirements
        run: pip install -r api/requirements.txt
      - name: Run tests and collect coverage
        run: pytest --cov=api.calculator --cov-report=xml
      - name: Upload coverage reports to Codecov with GitHub Action
        uses: codecov/codecov-action@v5
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          url: https://codecov.mycompany.com
          git_service: github_enterprise
```

Logs pulled from `codecov-api` contain the following relevant logs:
```
{
  "message": "Received upload request github_enterprise",
  "asctime": "2025-01-28 21:31:31,486",
  "name": "upload.views.legacy",
  "levelname": "INFO",
  "lineno": 90,
  "pathname": "/app/upload/views/legacy.py",
  "funcName": "post",
  "threadName": "MainThread",
  "taskName": null,
  "version": "github_enterprise",
  "query_params": {},
  "commit": null,
  "logger.name": "upload.views.legacy",
  "logger.thread_name": "MainThread",
  "level": "INFO"
}
{
  "message": "Failed to parse upload request params",
  "asctime": "2025-01-28 21:31:31,499",
  "name": "upload.views.legacy",
  "levelname": "WARNING",
  "lineno": 133,
  "pathname": "/app/upload/views/legacy.py",
  "funcName": "post",
  "threadName": "MainThread",
  "taskName": null,
  "request_params": { "version": "github_enterprise", "token": null },
  "errors": "{'commit': [ErrorDetail(string='required field', code='invalid')], 'version': [ErrorDetail(string='unallowed value github_enterprise', code='invalid')]}",
  "logger.name": "upload.views.legacy",
  "logger.thread_name": "MainThread",
  "level": "WARNING"
}
{
  "message": "Bad Request: /upload/github_enterprise/MyOrg::::codecov-demo/upload-coverage",
  "asctime": "2025-01-28 21:31:31,499",
  "name": "django.request",
  "levelname": "WARNING",
  "lineno": 241,
  "pathname": "/usr/local/lib/python3.12/site-packages/django/utils/log.py",
  "funcName": "log_response",
  "threadName": "MainThread",
  "taskName": null,
  "status_code": 400,
  "request": "<WSGIRequest: POST '/upload/github_enterprise/MyOrg::::codecov-demo/upload-coverage'>",
  "logger.name": "django.request",
  "logger.thread_name": "MainThread",
  "level": "WARNING"
}
```
