### ISSUE TITLE
Can't upload reports to new repo after erasing the Codecov repo and reactivating it with a new GitHub repo

### ISSUE THREAD

**Issue by k4b7** [codecov/feedback#656]
**Describe the bug**
I deleted a Codecov repo and then re-created it.  I did this because I had renamed the associated GitHub repo and created a new GitHub repo with the original name.  After doing that, I'm unable to get reports to show up in the Codecov repo.

**Environment (please complete the following information):**
I'm using GitHub Actions to run code coverage and upload reports to Codecov.  I'm using codecov/codecov-action@v5.  Here's a link to one of the GitHub Actions runs: https://github.com/escalier-lang/escalier/actions/runs/13469059378/job/37640177123?pr=4.  From the logs it looks like the upload was successful:
```
info - 2025-02-22 03:13:51,772 -- Found 1 coverage files to report
info - 2025-02-22 03:13:51,772 -- > /home/runner/work/escalier/escalier/coverage.out
info - 2025-02-22 03:13:52,235 -- Your upload is now processing. When finished, results will be available at: https://app.codecov.io/github/escalier-lang/escalier/commit/8aa6f320bdefee65b196a107be4f6c9905bb0eaf
info - 2025-02-22 03:13:52,334 -- Process Upload complete
```
When I visit https://app.codecov.io/github/escalier-lang/escalier/commit/8aa6f320bdefee65b196a107be4f6c9905bb0eaf, it says there are "Currently no uploads".

**To Reproduce**
1. Rename a GitHub repo in GitHub that's linked to a Codecov repo
2. Go to the "General Settings" for an existing Codecov repo
3. Click "Erase Repository" and erase the repo
4. Create a new GitHub repo with the original name of the renamed repo
6. Go to the Codecov GitHub App settings in the GitHub organization and give it access to the new repo
7. Go to the "General Settings" for Codecov repo and reactivate it
8. Create a PR to GitHub Actions workflow to upload reports to Codecov
9. Merge it into main
10. Create a new PR to test that uploading reports to Codecov is working
11. Click on the link provided by the Codecov action and see that no report was uploaded

**Expected behavior**
I expected the report to be uploaded.

**Screenshots**
<img width="807" alt="Image" src="https://github.com/user-attachments/assets/e61c0934-7b85-41e7-b706-12e0abb19383" />

**Additional Context**
Here's the GitHub Actions workflow file I'm using:
```yaml
name: Test and coverage

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  code_coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
      - run: go version
      - name: Run coverage
        run: go test ./... -race -coverprofile=coverage.out -covermode=atomic
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
```

Also, if I visit https://app.codecov.io/gh/escalier-lang/escalier it redirects me to https://app.codecov.io/gh/escalier-lang/escalier/new.

**Comment by k4b7** [comment]
I tried renaming the repo again, but that didn't seem to have an effect.  Then I copied exactly what's in the docs for the Go setup and it seems to be working now.

**Comment by k4b7** [comment]
Here's my updated workflow file:
```yaml
name: Test and coverage

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  code_coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: go test ./... -coverprofile=coverage.txt

      - name: Upload results to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
```
