### ISSUE TITLE
[Self-hosted] Use the same GLOBAL_UPLOAD_TOKEN for github_enterprise & github

### ISSUE THREAD

**Issue by nikosatwork** [codecov/feedback#712]
**Describe the bug**
We use a GLOBAL_UPLOAD_TOKEN for github_enterprise and recently integrated github too. However, it seems that we need to use a new GLOBAL_UPLOAD_TOKEN for github.

**Environment (please complete the following information):**
 - Browser: All
 - System: CI
 - Version: 25.4.1

**To Reproduce**
1. Setup github_enterprise & github a follows:

```
github_enterprise:
    url: https://github.cds.com
    api_url: https://github.cds.com/api/v3
    client_id: CLIENT_ID_GHE
    client_secret: CLIENT_SECRET_GHE
    webhook_secret: WEBHOOK_SECRET_GHE
    global_upload_token: GLOBAL_UPLOAD_TOKEN
    integration:
        id: 1
        pem: /codecov-secrets/scm_ca_cert_ghe.pem
github:
    client_id: CLIENT_ID_GH
    client_secret: CLIENT_SECRET_GH
    webhook_secret: WEBHOOK_SECRET_GH
    global_upload_token: GLOBAL_UPLOAD_TOKEN
    integration:
        id: 2
        pem: /codecov-secrets/scm_ca_cert_gh.pem
```

2. Make sure that the same GLOBAL_UPLOAD_TOKEN is used for both
3. Uploading fails with "Could not find a repository, try using repo upload token"
4. If using a separate GLOBAL_UPLOAD_TOKEN the upload is successful

**Expected behavior**
Using the same GLOBAL_UPLOAD_TOKEN for both github_enterprise & github does not fail the uploads
